// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: external.proto

#include "external.pb.h"
#include "external.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace ppca {
namespace rpc {

static const char* External_method_names[] = {
  "/ppca.rpc.External/Put",
  "/ppca.rpc.External/Get",
};

std::unique_ptr< External::Stub> External::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< External::Stub> stub(new External::Stub(channel));
  return stub;
}

External::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Put_(External_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(External_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status External::Stub::Put(::grpc::ClientContext* context, const ::ppca::rpc::PutRequest& request, ::ppca::rpc::PutReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Put_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::ppca::rpc::PutReply>* External::Stub::AsyncPutRaw(::grpc::ClientContext* context, const ::ppca::rpc::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ppca::rpc::PutReply>::Create(channel_.get(), cq, rpcmethod_Put_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::ppca::rpc::PutReply>* External::Stub::PrepareAsyncPutRaw(::grpc::ClientContext* context, const ::ppca::rpc::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ppca::rpc::PutReply>::Create(channel_.get(), cq, rpcmethod_Put_, context, request, false);
}

::grpc::Status External::Stub::Get(::grpc::ClientContext* context, const ::ppca::rpc::GetRequest& request, ::ppca::rpc::GetReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Get_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::ppca::rpc::GetReply>* External::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::ppca::rpc::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ppca::rpc::GetReply>::Create(channel_.get(), cq, rpcmethod_Get_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::ppca::rpc::GetReply>* External::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::ppca::rpc::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ppca::rpc::GetReply>::Create(channel_.get(), cq, rpcmethod_Get_, context, request, false);
}

External::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      External_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< External::Service, ::ppca::rpc::PutRequest, ::ppca::rpc::PutReply>(
          std::mem_fn(&External::Service::Put), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      External_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< External::Service, ::ppca::rpc::GetRequest, ::ppca::rpc::GetReply>(
          std::mem_fn(&External::Service::Get), this)));
}

External::Service::~Service() {
}

::grpc::Status External::Service::Put(::grpc::ServerContext* context, const ::ppca::rpc::PutRequest* request, ::ppca::rpc::PutReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status External::Service::Get(::grpc::ServerContext* context, const ::ppca::rpc::GetRequest* request, ::ppca::rpc::GetReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ppca
}  // namespace rpc

